#!/usr/bin/env -S "populate_pre_commit"
# Copyright 2022 John Tobin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # managed-by-populate-pre-commit start: actionlint.yaml
  - repo: local
    hooks:
    - id: actionlint
      name: Run `actionlint`
      language: system
      types:
      - yaml
      exclude: dependabot.yml|.*.yaml$
      entry: actionlint
  # managed-by-populate-pre-commit end: actionlint.yaml
  # managed-by-populate-pre-commit start: conventional-pre-commit.yaml
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
    - id: conventional-pre-commit
      stages:
      - commit-msg
      args:
      - --verbose
  # managed-by-populate-pre-commit end: conventional-pre-commit.yaml
  # managed-by-populate-pre-commit start: golang-coverage-check.yaml
  - repo: https://github.com/tobinjt/golang-coverage-check
    rev: v1.0
    hooks:
    - id: golang-coverage-check
  # managed-by-populate-pre-commit end: golang-coverage-check.yaml
  # managed-by-populate-pre-commit start: golang.yaml
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
    - id: go-build
    - id: go-fmt
    - id: go-imports
    - id: go-unit-tests
    - id: go-vet
  # managed-by-populate-pre-commit end: golang.yaml
  # managed-by-populate-pre-commit start: golangci-lint.yaml
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.2
    hooks:
    - id: golangci-lint
  # managed-by-populate-pre-commit end: golangci-lint.yaml
  # managed-by-populate-pre-commit start: hooks.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-illegal-windows-names
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: destroyed-symlinks
    - id: fix-byte-order-marker
    - id: mixed-line-ending
  # managed-by-populate-pre-commit end: hooks.yaml
  # managed-by-populate-pre-commit start: keep-sorted.yaml
  - repo: https://github.com/google/keep-sorted
    rev: v0.9.0
    hooks:
    - id: keep-sorted
  # managed-by-populate-pre-commit end: keep-sorted.yaml
  # managed-by-populate-pre-commit start: markdownlint.yaml
  - repo: local
    hooks:
    - id: markdownlint
      name: Run `markdownlint`
      language: system
      types:
      - markdown
      exclude: CODE_OF_CONDUCT.md
      entry: markdownlint
  # managed-by-populate-pre-commit end: markdownlint.yaml
  # managed-by-populate-pre-commit start: meta.yaml
  - repo: meta
    hooks:
    - id: check-hooks-apply
  # managed-by-populate-pre-commit end: meta.yaml
  # managed-by-populate-pre-commit start: spellcheck.yaml
  - repo: local
    hooks:
    - id: spellcheck
      stages:
      - commit-msg
      name: Check spelling
      language: system
      verbose: true
      entry: spell-check-wrapper
  # managed-by-populate-pre-commit end: spellcheck.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
